server:
  tomcat:
    remoteip:
      protocol-header: X-Forwarded-Proto
spring:
  security:
    user:
      name: aframeAdmin
      password: aframeSuper123
  boot:
    admin:
      ui:
        title: Aframe Monitor
