spring:
  datasource:
    url: jdbc:mysql://121.37.3.24:3306/aframe?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 121.37.3.24
    port: 6379
    password: admin123
