spring:
  profiles:
    active: test
server:
  port: 8081
  main:
    allow-bean-definition-overriding: true

sa-token:
  basic: ${spring.boot.admin.client.username}:${spring.boot.admin.client.password}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

logging:
  file:
    name: logs/aframe.log

mybatis-plus:
  mapper-locations: classpath*:mapper/*/*.xml
  global-config:
    db-config:
      # 数据库类型
      db-type: mysql

restful:
  enable: false

wechat:
  #公众号
  appId: wxa1ce438869e31a97
  secret: a1f8fbb6900812bfa0e98a80a54d4b41
  #开放平台
#  appId: wxe5385dfbe65dfb59
#  secret: 724bb3aa40a87c50796075d21b1f34cf
